# -*- coding: utf-8 -*-
"""Student performance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pd42A80bMjYiviFYeJGn1LPTKAXgRfm9

**Install Faker**
"""

pip install faker

from faker import Faker

fake = Faker()

"""**Data** **set**"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

names = [fake.name() for _ in range(250)]
data={
"student id":np.random.randint(18,65,250),
"Name":np.random.choice(names,250),
"Gender":np.random.choice(["Male","Female"],250),
"Department":np.random.choice(["IT","HR","Finance","Marketing","Sales"],250),
"Year":np.random.randint(2025,2028,250),
"Maths":np.random.randint(0,100,250),
"science":np.random.randint(0,100,250),
"English":np.random.randint(0,100,250),
"Attendence":np.random.randint(50,100,250),
"Internal mark":np.random.randint(0,25,250)
}

df=pd.DataFrame(data)

df

df.isnull().sum()

df["Total"] = df["Maths"] + df["science"] + df["English"]
df["Average"] = df["Total"] / 3

df["Grade"] = df["Average"].apply(lambda x: "A" if x>=85 else "B" if x>=70 else "C" if x>=50 else "Fail")

print("\nTop Students:\n", df.nlargest(5, "Average")[["Name","Average","Grade"]])

"""**Bar Chart**"""

plt.scatter(df["Attendence"], df["Average"])
plt.xlabel("Attendance")
plt.ylabel("Average Marks")
plt.title("Attendance vs Performance")
plt.show()

"""**Pie chart**"""

plt.figure()
df["Gender"].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Gender Distribution")
plt.ylabel("")
plt.show()

"""**Histogram**"""

plt.figure()
plt.hist(df["Average"], bins=10)
plt.title("Distribution of Average Marks")
plt.xlabel("Average Marks")
plt.ylabel("Frequency")
plt.show()

"""**Scatter plot**"""

plt.figure()
plt.scatter(df["Attendence"], df["Average"])
plt.title("Attendance vs Average Marks")
plt.xlabel("Attendance")
plt.ylabel("Average Marks")
plt.show()

